
# All values set here will be applied to the resource configuration prior to 
# calling parsl.load(config). Even if the key does't exist in the resource
# config, it will be added with the value defined here.
[resource_config_modifiers]
checkpoint_mode = 'task_exit'


# Values in the apps.XXX section will be passed as a dictionary to the corresponding
# app. e.g. apps.create_uri_manifest will be passed to the create_uri_manifest app.
[apps.create_manifest]
# The path to the staging directory
# e.g. "/gscratch/dirac/kbmod/workflow/staging"
staging_directory = "/home/drew/code/kbmod-wf/dev_staging"
output_directory = "/home/drew/code/kbmod-wf/dev_staging/single_chip_workflow"
file_pattern = "*.collection"


[apps.ic_to_wu]
# The path to the KBMOD search config file
# e.g. "/gscratch/dirac/kbmod/workflow/kbmod_search_config.yaml"
search_config_filepath = "/home/drew/code/kbmod-wf/dev_staging/search_config.yaml"

# The path to the butler config file that instantiate a butler to retrieve images
butler_config_filepath = "/gscratch/dirac/DEEP/repo/butler.yaml"

# Remove a previously created WU file if it exists
overwrite = false


[apps.reproject_wu]
# Number of processors to use for parallelizing the reprojection
n_workers = 32

# The name of the observation site to use for reflex correction
observation_site = "ctio"


[apps.kbmod_search]
# The path to the KBMOD search config file
# e.g. "/gscratch/dirac/kbmod/workflow/kbmod_search_config.yaml"
search_config_filepath = "/home/drew/code/kbmod-wf/dev_staging/search_config.yaml"
