# Example parsl config associated with 


# All values set here will be applied to the resource configuration prior to 
# calling parsl.load(config). Even if the key does't exist in the resource
# config, it will be added with the value defined here.
[resource_config_modifiers]
checkpoint_mode = 'task_exit'

# Values in the apps.XXX section will be passed as a dictionary to the corresponding
# app. e.g. apps.create_uri_manifest will be passed to the create_uri_manifest app.
[apps.get_uncertainties]

# The path of a resampled workunit to process
wu_path = "" # TODO update

# Path of a KBMOD results file produced from a run on the resampled workunit
res_path = "" # TODO Update

# If the KBMOD results has a uuid column only, get uncertainties for these uuids. Otherwise, get_uncertainties for all provided results.
# uuids = [] # Add if needed

# The output directory to write the file with uncertainties to 
output_dir = "" # TODO Update
